export type BlockComponentTypeMap = {
    "minecraft:inventory": BlockInventoryComponent,
    "minecraft:lavaContainer": BlockLavaContainerComponent,
    "minecraft:piston": BlockPistonComponent,
    "minecraft:potionContainer": BlockPotionContainerComponent,
    "minecraft:recordPlayer": BlockRecordPlayerComponent,
    "minecraft:sign": BlockSignComponent,
    "minecraft:snowContainer": BlockSnowContainerComponent,
    "minecraft:waterContainer": BlockWaterContainerComponent,
};

export type EntityComponentTypeMap = {
    "minecraft:addrider": EntityAddRiderComponent,
    "minecraft:ageable": EntityAgeableComponent,
    "minecraft:breathable": EntityBreathableComponent,
    "minecraft:can_climb": EntityCanClimbComponent,
    "minecraft:can_fly": EntityCanFlyComponent,
    "minecraft:can_power_jump": EntityCanPowerJumpComponent,
    "minecraft:color": EntityColorComponent,
    "minecraft:equippable": EntityEquippableComponent,
    "minecraft:fire_immune": EntityFireImmuneComponent,
    "minecraft:floats_in_liquid": EntityFloatsInLiquidComponent,
    "minecraft:flying_speed": EntityFlyingSpeedComponent,
    "minecraft:friction_modifier": EntityFrictionModifierComponent,
    "minecraft:ground_offset": EntityGroundOffsetComponent,
    "minecraft:healable": EntityHealableComponent,
    "minecraft:health": EntityHealthComponent,
    "minecraft:inventory": EntityInventoryComponent,
    "minecraft:is_baby": EntityIsBabyComponent,
    "minecraft:is_charged": EntityIsChargedComponent,
    "minecraft:is_chested": EntityIsChestedComponent,
    "minecraft:is_dyeable": EntityIsDyableComponent,
    "minecraft:is_hidden_when_invisible": EntityIsHiddenWhenInvisibleComponent,
    "minecraft:is_ignited": EntityIsIgnitedComponent,
    "minecraft:is_illager_captain": EntityIsIllagerCaptainComponent,
    "minecraft:is_saddled": EntityIsSaddledComponent,
    "minecraft:is_shaking": EntityIsShakingComponent,
    "minecraft:is_sheared": EntityIsShearedComponent,
    "minecraft:is_stackable": EntityIsStackableComponent,
    "minecraft:is_stunned": EntityIsStunnedComponent,
    "minecraft:is_tamed": EntityIsTamedComponent,
    "minecraft:item": EntityItemComponent,
    "minecraft:lava_movement": EntityLavaMovementComponent,
    "minecraft:leashable": EntityLeashableComponent,
    "minecraft:mark_variant": EntityMarkVariantComponent,
    "minecraft:tamemount": EntityMountTamingComponent,
    "minecraft:movement": EntityMovementComponent,
    "minecraft:movement.amphibious": EntityMovementAmphibiousComponent,
    "minecraft:movement.basic": EntityMovementBasicComponent,
    "minecraft:movement.fly": EntityMovementFlyComponent,
    "minecraft:movement.generic": EntityMovementGenericComponent,
    "minecraft:movement.glide": EntityMovementGlideComponent,
    "minecraft:movement.hover": EntityMovementHoverComponent,
    "minecraft:movement.jump": EntityMovementJumpComponent,
    "minecraft:movement.skip": EntityMovementSkipComponent,
    "minecraft:movement.sway": EntityMovementSwayComponent,
    "minecraft:navigation.climb": EntityNavigationClimbComponent,
    "minecraft:navigation.float": EntityNavigationFloatComponent,
    "minecraft:navigation.fly": EntityNavigationFlyComponent,
    "minecraft:navigation.generic": EntityNavigationGenericComponent,
    "minecraft:navigation.hover": EntityNavigationHoverComponent,
    "minecraft:navigation.walk": EntityNavigationWalkComponent,
    "minecraft:npc": EntityNpcComponent,
    "minecraft:onfire": EntityOnFireComponent,
    "minecraft:push_through": EntityPushThroughComponent,
    "minecraft:rideable": EntityRideableComponent,
    "minecraft:riding": EntityRidingComponent,
    "minecraft:scale": EntityScaleComponent,
    "minecraft:skin_id": EntitySkinIdComponent,
    "minecraft:strength": EntityStrengthComponent,
    "minecraft:tameable": EntityTameableComponent,
    "minecraft:underwater_movement": EntityUnderwaterMovementComponent,
    "minecraft:variant": EntityVariantComponent,
    "minecraft:wants_jockey": EntityWantsJockeyComponent,
};

export type ItemComponentTypeMap = {
    "minecraft:cooldown": ItemCooldownComponent,
    "minecraft:durability": ItemDurabilityComponent,
    "minecraft:enchantments": ItemEnchantsComponent,
    "minecraft:food": ItemFoodComponent,
};
